### ISSUE TITLE
Some patches do not parse

### ISSUE THREAD

**Issue by moio** [moio/pase#1]
```
> java -jar pase/target/pase-0.1-SNAPSHOT.jar search ./opensuse-index/ ./opensuse/bazel2.0-2.0.0-lp152.3.2.src.rpm_contents/bazel-2.0.0-dist.zip_contents/third_party/aws-sdk-auth-lite/patches-vs-1.11.297/01-bazel-strip-unused.patch

Exception in thread "main" com.github.difflib.unifieddiff.UnifiedDiffParserException: expected file start line not found
        at com.github.difflib.unifieddiff.UnifiedDiffReader.parse(UnifiedDiffReader.java:90)
        at com.github.difflib.unifieddiff.UnifiedDiffReader.parseUnifiedDiff(UnifiedDiffReader.java:136)
        at com.suse.pase.PatchParser.parsePatch(PatchParser.java:26)
        at com.suse.pase.Main.search(Main.java:39)
        at com.suse.pase.Main.main(Main.java:17)
```

**Comment by moio** [comment]
https://github.com/java-diff-utils/java-diff-utils/issues/107
